/**
 * Slices `Quest.ActivationInstance` out of the real `Quest.cs`.
 *
 * This is where a scenario's activation text becomes what the player reads:
 * translated, `{0}` filled in, symbols replaced, newlines unescaped. It is
 * Unity-free apart from the game type and a random hero, both of which the
 * harness supplies, so it can be compiled and compared directly rather than
 * transcribed.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')
const source = readFileSync(join(repo, 'unity/Assets/Scripts/Quest/Quest.cs'), 'utf8')

/** Takes a declaration through its matching brace, skipping literals. */
function slice(signature) {
  const start = source.indexOf(signature)
  if (start === -1) throw new Error(`${signature} not found — the port needs rechecking`)

  let depth = 0
  let inString = false
  let inChar = false
  let inLineComment = false

  for (let i = source.indexOf('{', start); i < source.length; i++) {
    const c = source[i]
    const previous = source[i - 1]

    if (inLineComment) {
      if (c === '\n') inLineComment = false
      continue
    }
    if (inString) {
      if (c === '"' && previous !== '\\') inString = false
      continue
    }
    if (inChar) {
      if (c === "'" && previous !== '\\') inChar = false
      continue
    }

    if (c === '"') inString = true
    else if (c === "'") inChar = true
    else if (c === '/' && source[i + 1] === '/') inLineComment = true
    else if (c === '{') depth++
    else if (c === '}' && --depth === 0) return source.slice(start, i + 1)
  }
  throw new Error(`unbalanced braces after ${signature}`)
}

const generated = `// Generated by extract.mjs from
// unity/Assets/Scripts/Quest/Quest.cs — do not edit.
using System;
using System.Collections.Generic;
using Assets.Scripts.Content;

public partial class Quest
{
${slice('public class ActivationInstance')}
}
`

writeFileSync(join(here, 'Extracted.cs'), generated)
console.log(`extracted ${generated.split('\n').length} lines`)
