// Shared differential-test corpus. Deliberately includes inputs I expect to
// diverge, so the divergences get recorded rather than discovered later.
const s = (name, input) => ({ name, kind: 'readFromString', input })
const sec = (name, lines, section) => ({ name, kind: 'readSection', lines, section })

export const corpus = [
  s('basic', '[S]\na=1\nb=2'),
  s('multi-section', '[A]\na=1\n\n[B]\nb=2'),
  s('comment-hash', '# c\n[S]\na=1'),
  s('comment-semi', '[S]\n; c\na=1'),
  s('comment-indented', '[S]\n   # c\n   ; c2\na=1'),
  s('comment-hash-midline', '[S]\na=1 # not a comment'),
  s('comment-semi-midline', '[S]\na=1 ; not a comment'),
  s('key-no-value', '[S]\nflag'),
  s('quoted', '[S]\na="q v"'),
  s('quoted-doubled', '[S]\na=""dd""'),
  s('quoted-unbalanced-left', '[S]\na="left'),
  s('quoted-unbalanced-right', '[S]\na=right"'),
  s('quoted-inner-space', '[S]\na=  " p "  '),
  s('quote-in-middle', '[S]\na=x"y'),
  s('empty-input', ''),
  s('whitespace-around', '[S]\n  a  =  1  '),
  s('tabs-around', '[S]\n\ta\t=\t1\t'),
  s('whitespace-only-line', '[S]\n   \na=1'),
  s('tab-only-line', '[S]\n\t\na=1'),
  s('nbsp-only-line', '[S]\n \na=1'),
  s('dup-section', '[S]\na=1\n\n[S]\nb=2'),
  s('dup-key', '[S]\na=first\na=second'),
  s('dup-key-novalue', '[S]\nflag\nflag'),
  s('equals-in-value', '[S]\na=x=y=z'),
  s('empty-value', '[S]\na='),
  s('empty-key', '[S]\n=v'),
  s('just-equals', '[S]\n='),
  s('nested-brackets', '[[N]]\na=1'),
  s('unterminated-section', '[U\na=1'),
  s('empty-section-name', '[]\na=1\n[S]\nb=2'),
  s('bracket-only-open', '[\na=1'),
  s('section-trailing-text', '[S] extra\na=1'),
  s('section-indented', '   [S]\na=1'),
  s('pre-section-data', 'orphan=1\n[S]\na=2'),
  s('crlf', '[S]\r\na=1\r\nb=2'),
  s('cr-only', '[S]\ra=1\rb=2'),
  s('blank-lines', '[S]\n\n\na=1\n\n'),
  s('unicode-value', '[S]\na=äöü 日本語'),
  s('unicode-key', '[S]\nnøkkel=v'),
  s('proto-key', '[__proto__]\n__proto__=p\nconstructor=c'),
  s('case-sensitivity', '[S]\nKey=1\nkey=2'),
  s('semicolon-in-value', '[S]\na=x;y'),
  s('hash-section', '#[S]\na=1'),
  s('value-with-brackets', '[S]\na=[not a section]'),
  s('multiple-equals-spaces', '[S]\na = = b'),
  s('section-then-eof', '[S]'),
  s('only-comments', '# a\n; b'),

  sec('sec-basic', ['[Q]', 'a=1', 'b=2', '[O]', 'c=3'], 'Q'),
  sec('sec-missing', ['[Q]', 'a=1'], 'Nope'),
  sec('sec-indented-header-not-end', ['[Q]', 'a=1', '  [X]', 'b=2'], 'Q'),
  sec('sec-dup-novalue', ['[S]', 'flag', 'flag'], 'S'),
  sec('sec-dup-key', ['[S]', 'a=1', 'a=2'], 'S'),
  sec('sec-comment', ['[S]', '; c', 'a=1'], 'S'),
  sec('sec-hash-comment', ['[S]', '# c', 'a=1'], 'S'),
  sec('sec-whitespace-line', ['[S]', '   ', 'a=1'], 'S'),
  sec('sec-quoted', ['[S]', 'a="q"'], 'S'),
  sec('sec-prefix-match', ['[Quest]', 'a=1', '[QuestText]', 'b=2'], 'Quest'),
  sec('sec-header-trailing', ['[S] junk', 'a=1'], 'S'),
  sec('sec-empty-section', ['[S]', '[T]', 'a=1'], 'S'),
]
