/**
 * Slices the attack-selection methods out of the real sources.
 *
 * `GetAttackTypes` and `GetRandomAttack` come from `ContentTypes.cs`, and the
 * `QuestMonster` override from `QuestMonster.cs`. Both files are far too
 * Unity-bound to compile whole, but these four methods reach only for the
 * content list and the random source, which the harness supplies.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')

/** Takes a declaration through its matching brace, skipping literals. */
function slice(source, signature) {
  const start = source.indexOf(signature)
  if (start === -1) throw new Error(`${signature} not found — the port needs rechecking`)

  let depth = 0
  let inString = false
  let inChar = false
  let inLineComment = false

  for (let i = source.indexOf('{', start); i < source.length; i++) {
    const c = source[i]
    const previous = source[i - 1]

    if (inLineComment) {
      if (c === '\n') inLineComment = false
      continue
    }
    if (inString) {
      if (c === '"' && previous !== '\\') inString = false
      continue
    }
    if (inChar) {
      if (c === "'" && previous !== '\\') inChar = false
      continue
    }

    if (c === '"') inString = true
    else if (c === "'") inChar = true
    else if (c === '/' && source[i + 1] === '/') inLineComment = true
    else if (c === '{') depth++
    else if (c === '}' && --depth === 0) return source.slice(start, i + 1)
  }
  throw new Error(`unbalanced braces after ${signature}`)
}

const types = readFileSync(join(repo, 'unity/Assets/Scripts/Content/ContentTypes.cs'), 'utf8')
const questMonster = readFileSync(join(repo, 'unity/Assets/Scripts/Quest/QuestMonster.cs'), 'utf8')

const generated = `// Generated by extract.mjs from
// unity/Assets/Scripts/Content/ContentTypes.cs and
// unity/Assets/Scripts/Quest/QuestMonster.cs — do not edit.
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Assets.Scripts.Content;
using ValkyrieTools;

public class MonsterData : GenericData
{
    public static string type = "Monster";
    public StringKey name = StringKey.NULL;

${slice(types, 'virtual public IEnumerable<string> GetAttackTypes()')}

${slice(types, 'virtual public StringKey GetRandomAttack(string type)')}
}

public class QuestMonster : MonsterData
{
    public CustomMonsterStub cMonster = new CustomMonsterStub();

${slice(questMonster, 'override public StringKey GetRandomAttack(string type)')}
}
`

writeFileSync(join(here, 'Extracted.cs'), generated)
console.log(`extracted ${generated.split('\n').length} lines`)
