/**
 * Slices the symbol-replacement code out of the real `EventManager.cs`.
 *
 * `OutputSymbolReplace` runs over the text of every event a quest shows, so
 * getting it wrong is visible everywhere. It is one of the few parts of the
 * play loop that is Unity-free enough to extract: it touches `Game.Get()` only
 * for the game type and the quest's variables, both of which the harness
 * supplies.
 *
 * `CHARS_MAP` and `CHAR_PACKS_MAP` come across as data, so the character
 * tables are the shipped ones rather than a transcription.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')
const source = readFileSync(join(repo, 'unity/Assets/Scripts/Quest/EventManager.cs'), 'utf8')

/**
 * Takes a declaration through its matching closing brace.
 *
 * Braces inside string and character literals are skipped. This code is full
 * of them — `"{var:"`, `"{heart}"` — and counting those makes the slice run
 * past the end of the method into whatever follows.
 */
function slice(signature) {
  const start = source.indexOf(signature)
  if (start === -1) throw new Error(`${signature} not found — the port needs rechecking`)

  let depth = 0
  let inString = false
  let inChar = false
  let inLineComment = false

  for (let i = source.indexOf('{', start); i < source.length; i++) {
    const c = source[i]
    const previous = source[i - 1]

    if (inLineComment) {
      if (c === '\n') inLineComment = false
      continue
    }
    if (inString) {
      if (c === '"' && previous !== '\\') inString = false
      continue
    }
    if (inChar) {
      if (c === "'" && previous !== '\\') inChar = false
      continue
    }

    if (c === '"') inString = true
    else if (c === "'") inChar = true
    else if (c === '/' && source[i + 1] === '/') inLineComment = true
    else if (c === '{') depth++
    else if (c === '}' && --depth === 0) {
      // A field initialiser ends at the semicolon after its brace.
      return source.slice(start, source[i + 1] === ';' ? i + 2 : i + 1)
    }
  }
  throw new Error(`unbalanced braces after ${signature}`)
}

const parts = [
  slice('public static string OutputSymbolReplace(string input)'),
  slice('public static string InputSymbolReplace(string input)'),
  slice('public static Dictionary<string, string> GetCharacterMap('),
  slice('public static Dictionary<string, Dictionary<string, string>> CHARS_MAP'),
  slice('public static Dictionary<string, Dictionary<string, string>> CHAR_PACKS_MAP'),
]

const generated = `// Generated by extract.mjs from
// unity/Assets/Scripts/Quest/EventManager.cs — do not edit.
using System;
using System.Collections.Generic;

public static class EventManager
{
${parts.join('\n\n')}
}
`

writeFileSync(join(here, 'Extracted.cs'), generated)
console.log(`extracted ${generated.split('\n').length} lines`)
