/**
 * Generates `packages/core/src/quest/characterMap.ts` from
 * `unity/Assets/Scripts/Quest/EventManager.cs`.
 *
 * Quest text uses markers like `{heart}` that map to glyphs in the game font,
 * and the mapping differs per game. Generating rather than retyping keeps the
 * tables identical to the shipped ones and makes a drift obvious.
 *
 *   node tools/differential/symbols/generate-tables.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')
const source = readFileSync(join(repo, 'unity/Assets/Scripts/Quest/EventManager.cs'), 'utf8')

/** Brace-matches from a declaration, skipping string literals. */
function body(name) {
  const at = source.indexOf(`public static Dictionary<string, Dictionary<string, string>> ${name}`)
  if (at === -1) throw new Error(`${name} not found in EventManager.cs`)

  let depth = 0
  let inString = false
  const start = source.indexOf('{', at)

  for (let i = start; i < source.length; i++) {
    const c = source[i]
    if (inString) {
      if (c === '"' && source[i - 1] !== '\\') inString = false
      continue
    }
    if (c === '"') inString = true
    else if (c === '{') depth++
    else if (c === '}' && --depth === 0) return source.slice(start, i + 1)
  }
  throw new Error(`unbalanced braces in ${name}`)
}

/** Only `\\"` and `\\\\` are real escapes here; the glyphs are literal UTF-8. */
const unescape = (text) => text.replace(/\\(["\\])/g, '$1')

function parse(name) {
  const out = {}
  const games =
    /\{\s*"(D2E|MoM|IA)"\s*,\s*new Dictionary<string,\s*string>\(\)\s*\{([\s\S]*?)\n\s*\}\s*\}/g

  for (const game of body(name).matchAll(games)) {
    const pairs = {}
    for (const pair of game[2].matchAll(
      /\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}/g,
    )) {
      pairs[unescape(pair[1])] = unescape(pair[2])
    }
    out[game[1]] = pairs
  }
  return out
}

const chars = parse('CHARS_MAP')
const packs = parse('CHAR_PACKS_MAP')

const file = `/**
 * Character tables, generated by tools/differential/symbols/generate-tables.mjs
 * from unity/Assets/Scripts/Quest/EventManager.cs — do not edit.
 *
 * Quest text uses markers like \`{heart}\` that map to glyphs in the game
 * font. The mapping differs per game, which is why it is keyed by game type.
 */

export const CHARS_MAP: Record<string, Record<string, string>> = ${JSON.stringify(chars, null, 2)}

export const CHAR_PACKS_MAP: Record<string, Record<string, string>> = ${JSON.stringify(packs, null, 2)}
`

writeFileSync(join(here, '../../../packages/core/src/quest/characterMap.ts'), file)
console.log(
  `generated ${Object.keys(chars).length} character maps, ` +
    `${Object.keys(packs).length} pack maps`,
)
