/**
 * Slices the testable `FindLocalisedMultimediaFile` overload out of the real
 * `Quest.cs` and wraps it in a compilable class.
 *
 * Quest.cs itself cannot be compiled here — it pulls in most of UnityEngine —
 * but this one overload touches nothing beyond System.IO. Extracting it
 * mechanically keeps the code under test byte-identical to what ships, rather
 * than a hand-copy that could drift.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')
const source = readFileSync(join(repo, 'unity/Assets/Scripts/Quest/Quest.cs'), 'utf8')

const SIGNATURE =
  'public static string FindLocalisedMultimediaFile(string name, string source, string currentLang, string fallbackLang, bool editMode)'

const start = source.indexOf(SIGNATURE)
if (start === -1) throw new Error(`${SIGNATURE} not found in Quest.cs — the port needs rechecking`)

// Take the signature through its matching closing brace.
let depth = 0
let end = -1
for (let i = source.indexOf('{', start); i < source.length; i++) {
  if (source[i] === '{') depth++
  else if (source[i] === '}' && --depth === 0) {
    end = i + 1
    break
  }
}
if (end === -1) throw new Error('unbalanced braces after the signature')

const method = source.slice(start, end)
const generated = `// Generated by extract.mjs from unity/Assets/Scripts/Quest/Quest.cs — do not edit.
using System.IO;

public static class Quest
{
${method
  .split('\n')
  .map((line) => (line.length === 0 ? line : `    ${line.replace(/^ {4}/, '')}`))
  .join('\n')}
}
`

writeFileSync(join(here, 'Quest.Extracted.cs'), generated)
console.log(`extracted ${method.split('\n').length} lines`)
