<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>disable</Nullable>
    <AssemblyName>multimediaharness</AssemblyName>
    <RootNamespace>MultimediaHarness</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Quest.Extracted.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
