/**
 * Character tables, generated by tools/differential/symbols/generate-tables.mjs
 * from unity/Assets/Scripts/Quest/EventManager.cs — do not edit.
 *
 * Quest text uses markers like `{heart}` that map to glyphs in the game
 * font. The mapping differs per game, which is why it is keyed by game type.
 */

export const CHARS_MAP: Record<string, Record<string, string>> = {
  D2E: {
    '{heart}': '≥',
    '{fatigue}': '∏',
    '{might}': '∂',
    '{will}': 'π',
    '{action}': '∞',
    '{knowledge}': '∑',
    '{awareness}': 'μ',
    '{shield}': '≤',
    '{surge}': '±',
  },
  MoM: {
    '{will}': '',
    '{action}': '',
    '{strength}': '',
    '{agility}': '',
    '{lore}': '',
    '{influence}': '',
    '{observation}': '',
    '{success}': '',
    '{clue}': '',
  },
}

export const CHAR_PACKS_MAP: Record<string, Record<string, string>> = {
  MoM: {
    '{MAD01}': '',
    '{MAD06}': '',
    '{MAD09}': '',
    '{MAD20}': '',
    '{MAD21}': '',
    '{MAD22}': '',
    '{MAD23}': '',
    '{MAD25}': '',
    '{MAD26}': '',
    '{MAD27}': '',
    '{MAD28}': '',
  },
}
