/**
 * Slices the `SelectionItemTraits` and `TraitGroup` classes out of the real
 * `UIWindowSelectionListTraits.cs` and wraps them so they compile.
 *
 * The file as a whole is uGUI-bound and cannot leave Unity, but these two
 * classes touch nothing beyond LINQ and a translated string, which the harness
 * supplies. Extracting mechanically keeps the code under test identical to
 * what ships and fails loudly if either class moves.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')
const traitsFile = readFileSync(
  join(repo, 'unity/Assets/Scripts/UI/UIWindowSelectionListTraits.cs'),
  'utf8',
)
const listFile = readFileSync(
  join(repo, 'unity/Assets/Scripts/UI/UIWindowSelectionList.cs'),
  'utf8',
)

/** Takes a class declaration through its matching closing brace. */
function sliceClass(signature, source = traitsFile) {
  const start = source.indexOf(signature)
  if (start === -1) throw new Error(`${signature} not found — the port needs rechecking`)

  let depth = 0
  for (let i = source.indexOf('{', start); i < source.length; i++) {
    if (source[i] === '{') depth++
    else if (source[i] === '}' && --depth === 0) return source.slice(start, i + 1)
  }
  throw new Error(`unbalanced braces after ${signature}`)
}

const base = sliceClass('public class SelectionItem\n', listFile)
const item = sliceClass('public class SelectionItemTraits : SelectionItem')
const group = sliceClass('protected class TraitGroup')

const generated = `// Generated by extract.mjs from
// unity/Assets/Scripts/UI/UIWindowSelectionListTraits.cs — do not edit.
using System;
using System.Collections.Generic;
using System.Linq;

// UnityEngine.Color, reduced to what SelectionItem stores. Nothing under test
// reads it; it is here so the extracted source compiles unmodified.
public struct Color
{
    public float r, g, b, a;
    public Color(float r, float g, float b, float a = 1f) { this.r = r; this.g = g; this.b = b; this.a = a; }
    public static Color white => new Color(1f, 1f, 1f, 1f);
}

public static class Extracted
{
${base}

${item}

${group.replace('protected class TraitGroup', 'public class TraitGroup').replace('protected TraitGroupFilterMode _filterMode', 'public TraitGroupFilterMode _filterMode').replace('protected enum TraitGroupFilterMode', 'public enum TraitGroupFilterMode')}
}
`

writeFileSync(join(here, 'Extracted.cs'), generated)
console.log(`extracted ${generated.split('\n').length} lines`)
