/**
 * Slices `MonsterDialogMoM.Defeated` out of the real `MonsterDialogMoM.cs`.
 *
 * Defeating a monster is engine behaviour wearing a dialog's clothes: it
 * removes the monster, fires two triggers and can drive the monster phase
 * onward. Transcribing it into a shim would mean comparing the port against a
 * copy of itself, so it is extracted and compiled instead.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '../../../..')
const source = readFileSync(join(repo, 'unity/Assets/Scripts/Quest/MonsterDialogMoM.cs'), 'utf8')

/** Takes a declaration through its matching brace, skipping literals. */
function slice(signature) {
  const start = source.indexOf(signature)
  if (start === -1) throw new Error(`${signature} not found — the port needs rechecking`)

  let depth = 0
  let inString = false
  let inChar = false
  let inLineComment = false

  for (let i = source.indexOf('{', start); i < source.length; i++) {
    const c = source[i]
    const previous = source[i - 1]

    if (inLineComment) {
      if (c === '\n') inLineComment = false
      continue
    }
    if (inString) {
      if (c === '"' && previous !== '\\') inString = false
      continue
    }
    if (inChar) {
      if (c === "'" && previous !== '\\') inChar = false
      continue
    }

    if (c === '"') inString = true
    else if (c === "'") inChar = true
    else if (c === '/' && source[i + 1] === '/') inLineComment = true
    else if (c === '{') depth++
    else if (c === '}' && --depth === 0) return source.slice(start, i + 1)
  }
  throw new Error(`unbalanced braces after ${signature}`)
}

const generated = `// Generated by extract.mjs from
// unity/Assets/Scripts/Quest/MonsterDialogMoM.cs — do not edit.
using System;

public static class MonsterDialogMoM
{
${slice('public static void Defeated(Quest.Monster monster)')}
}
`

writeFileSync(join(here, 'Extracted.cs'), generated)
console.log(`extracted ${generated.split('\n').length} lines`)
