<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>i18nharness</AssemblyName>
    <RootNamespace>i18nharness</RootNamespace>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RollForward>LatestMajor</RollForward>
    <NoWarn>CS0649;CS0414</NoWarn>
  </PropertyGroup>
</Project>
