<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>questharness</AssemblyName>
    <RootNamespace>questharness</RootNamespace>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RollForward>LatestMajor</RollForward>
    <NoWarn>CS0649;CS0414;CS0108;CS0114;CS8981;CS0169</NoWarn>
  </PropertyGroup>
</Project>
